### ISSUE TITLE
Looks like some points are missing in the documentation

### ISSUE THREAD

**Issue by spyesx** [anonaddy/docker#108]
Hi,

I'm trying to enable SMTP TLS on a Docker + Traefik/LetsEncrypt stack. I've set these 2 variables to `true`:

```bash
POSTFIX_SMTPD_TLS=true
POSTFIX_SMTP_TLS=true
```

However, I can't figure out the next steps and what to do with these variables:

```
POSTFIX_SMTPD_TLS_CERT_FILE
POSTFIX_SMTPD_TLS_KEY_FILE
POSTFIX_SMTP_TLS
POSTFIX_RELAYHOST
POSTFIX_RELAYHOST_AUTH_ENABLE
POSTFIX_RELAYHOST_USERNAME
POSTFIX_RELAYHOST_PASSWORD
```

Basically, all email received by Gmail are marked as "domain.tld did not encrypt this message" and they end up in SPAM.

1. Am I on the right track with Postfix TLS?
2. If yes, how to implement it?

**Comment by spyesx** [comment]
Answering my own question. I ended up using [ldez/traefik-certs-dumper](https://github.com/ldez/traefik-certs-dumper).

This project helps to get around this issue: https://github.com/traefik/traefik/issues/2418

For those who need to support Consul, there is also this project: https://github.com/SvenDowideit/traefik-certdumper

**Comment by crazy-max** [comment]
Sorry I miss your issue. Yes I use myself traefik cert dumper for this use case. I guess some documentation would be nice agree. Feel free to open a PR!

**Comment by spyesx** [comment]
I wasn't the only one working on update of the documentation and some examples: https://github.com/anonaddy/docker/pull/55. This PR is on its way for approval. I'll let it here.
