### ISSUE TITLE
Sending mails from alias fails after upgrading to version 0.10.0

### ISSUE THREAD

**Issue by croxxx** [anonaddy/docker#113]
### Behaviour

After upgrading to 0.10.0 recently I noticed sending mails now causes an error claiming SPF/DMARC validation to have failed.
Attempting to send a mail results in a message like the following being generated.
![anonaddy](https://user-images.githubusercontent.com/5447834/155473699-27262c01-5325-45c4-a08a-dfabb2d60fbc.png)
When checking rspamd for more details, it looks to me everything is as it should be.
![rspamd](https://user-images.githubusercontent.com/5447834/155473798-f2b5198e-e15a-4115-b908-07e0738664b7.png)

#### Expected behaviour

> Mails are sent as they were in version 0.9.0 and earlier.

#### Actual behaviour

> Mails are not sent despite passing required checks as outlined above.

### Assumption

I have noticed the configuration file `/etc/rspamd/local.d/milter_headers.conf` to have the following content:
```
use = ["authentication-results", "remove-headers", "spam-header"];

routines {
  remove-headers {
    headers {
      "X-Spam" = 0;
      "X-Spamd-Bar" = 0;
      "X-Spam-Level" = 0;
      "X-Spam-Status" = 0;
      "X-Spam-Flag" = 0;
    }
  }
  authentication-results {
    header = "X-AnonAddy-Authentication-Results";
    remove = 0;
  }
  spam-header {
    header = "X-AnonAddy-Spam";
    value = "Yes";
    remove = 0;
  }
}
```
This is not aligned with the required changes listed in the [0.10.0 release notes](https://github.com/anonaddy/anonaddy/releases/tag/v0.10.0) suggesting the following:
```
use = ["authentication-results", "remove-headers", "spam-header", "add_dmarc_allow_header"];

routines {
  remove-headers {
    headers {
      "X-Spam" = 0;
      "X-Spamd-Bar" = 0;
      "X-Spam-Level" = 0;
      "X-Spam-Status" = 0;
      "X-Spam-Flag" = 0;
    }
  }
  authentication-results {
    header = "X-AnonAddy-Authentication-Results";
    remove = 0;
  }
  spam-header {
    header = "X-AnonAddy-Spam";
    value = "Yes";
    remove = 0;
  }
}

custom {
  add_dmarc_allow_header = <<EOD
return function(task, common_meta)
  if task:has_symbol('DMARC_POLICY_ALLOW') then
    return nil,
    {['X-AnonAddy-Dmarc-Allow'] = 'Yes'},
    {['X-AnonAddy-Dmarc-Allow'] = 0},
    {}
  end

  return nil,
  {},
  {['X-AnonAddy-Dmarc-Allow'] = 0},
  {}
end
EOD;
}
```
As noted there, the mail provider used here seemingly does not enforce its (perfectly valid) DMARC policy, probably causing the issue in the process.

### Suggestion

Apply the changes suggested in the release notes.

If this is indeed intended to happen, it would be great to have information about how to configure this behaviour in order to allow such providers to be used regardless.
Despite being a potential spoofing risk, the sheer amount of people using one of the providers affected makes the viability of enforcing a certain policy questionable at this point.

---

**Edit:** When manually patching in an updated version of the filter rules into the container the mail was sent fine just now.

**Comment by willbrowningme** [comment]
I've added the required Rspamd `milter_headers.conf` changes now - https://github.com/anonaddy/docker/blob/master/rootfs/etc/cont-init.d/14-config-rspamd.sh#L133

**Comment by crazy-max** [comment]
Oh I missed that one from the release notes!
