### ISSUE TITLE
Cannot migrate to latest tag

### ISSUE THREAD

**Issue by slurdge** [anonaddy/docker#118]
Hello,

My anonaddy instance worked nicely so far. I tried to upgrade to 0.11, but when doing so it fails starting the container with the following error:
```
anonaddy    | Migrating: 2022_02_25_091005_move_account_username_to_usernames_table
anonaddy    |
anonaddy    | In Connection.php line 712:
anonaddy    |
anonaddy    |   SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i
anonaddy    |   n your SQL syntax; check the manual that corresponds to your MariaDB server
anonaddy    |    version for the right syntax to use near 'index `additional_usernames_user
anonaddy    |   name_unique` to `usernames_username_unique`' at line 1 (SQL: alter table `u
anonaddy    |   sernames` rename index `additional_usernames_username_unique` to `usernames
anonaddy    |   _username_unique`)
anonaddy    |
```

I tried to force a 0.10 tag but now I get a 500 internal error. I'm not sure what I am supposed to do with the database in order to fix the situation.

**Comment by willbrowningme** [comment]
It looks like that has failed on this line of the migration - https://github.com/anonaddy/anonaddy/blob/master/database/migrations/2022_02_25_091005_move_account_username_to_usernames_table.php#L23

Are you able to try manually running:

```sql
alter table `usernames` rename index `additional_usernames_username_unique` to `usernames
anonaddy_username_unique;
```

From the mysql cli to see if the same error is returned?

If you need to revert these changes and go back to the previous release then you just need to downgrade and rename the `usernames` table back to `additional_usernames` and it should work again.

I'll try to see what this issue is, all my tests are working as expected.

**Comment by slurdge** [comment]
Yes, the error is the same:
```
MariaDB [anonaddy]> alter table `usernames` rename index `additional_usernames_username_unique` to `usernames_username_unique`;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'index `additional_usernames_username_unique` to `usernames_username_unique`' at line 1
```

**Comment by slurdge** [comment]
I found the error. It came from mariadb version. I had 10.4 in my docker-compose where as 10.5 is needed.
When I upgraded to 10.5, @willbrowningme your command worked. From this point I did reverse everything I did;
```mysql
rename table usernames to additional_usernames;
alter table `additional_usernames` rename index `usernames_username_unique` to `additional_usernames_username_unique`;
```

And the migration worked correctly. Thank you for the help, I it greatly appreciated.

**Comment by willbrowningme** [comment]
Ah great stuff, nice find! Yes that's a good idea.

**Comment by slurdge** [comment]
Unfortunately I stumble on another block: now anonaddy is running, but it seems there is a problem with the stored procedure 'check_access':
```bash
warning: mysql:/etc/postfix/mysql-recipient-access.cf: query failed: Truncated incorrect DOUBLE value: 'mydomain.com'
```

The only location I see it is inside the username check:
```mysql
alias_domain IN (CONCAT(username, '.mydomain.com') = '%s') ) AS usernames,
```

It does the same error if it is on `mydomain.com` or `user.mydomain.com`

**Comment by slurdge** [comment]
I'm trying to debug right now.
If I do from mysql:
```mysql
MariaDB [anonaddy]> CALL check_access('test_not_created@mydomain.com');
ERROR 1292 (22007): Truncated incorrect DOUBLE value: 'mydomain.com'
```
Same with any subdomain, be the alias created or not. However with an alias that is created but disabled I get:
```mysql
MariaDB [anonaddy]> CALL check_access('test@mydomain.com');
+-------------------------------+
| alias_action                  |
+-------------------------------+
| REJECT Address does not exist |
+-------------------------------+
1 row in set (0.002 sec)

Query OK, 1 row affected (0.002 sec)
```

If I test with an alias created but not disabled:
```mysql
MariaDB [anonaddy]> CALL check_access('alias_created@mydomain.com');
ERROR 1292 (22007): Truncated incorrect DOUBLE value: 'mydomain.com'
```

**Comment by slurdge** [comment]
I do not understand this line:
https://github.com/anonaddy/docker/blob/106bd3e7d32bd2ddcbaaf38230a4610204417bc5/rootfs/etc/cont-init.d/15-config-postfix.sh#L270
```mysql
                alias_domain IN (${QUERY_USERNAMES}) ) AS usernames,
```
Seems it will do a '=%s' on top of the CONTACT but I can't understand why.

If I change inside `15-config-postfix.sh` to a simple:
```mysql
 FROM
                usernames
            WHERE
                alias_domain IN ( CONCAT(username, '.mydomain.com') ) ) AS usernames,
            (
            SELECT
```
It answers 'DUNNO' for non existing (but autocreated) aliases, 'DUNNO' for existing activated aliases, 'REJECT'/'DISCARD' for alias removed/deactivated.

Also, I am suprised by the fact that 'QUERY_USERNAME' will have an 'OR' clause whereas on the original code it is separated with ',':
```
IN (CONCAT(username, '.example.com'),CONCAT(username, '.example2.com'))
```
Here: https://github.com/anonaddy/anonaddy/blob/c784c7ec8453f5bbaa4feec413e87957751566af/SELF-HOSTING.md?plain=1#L656

**Comment by slurdge** [comment]
I think I found the bug:
https://github.com/anonaddy/docker/pull/117/commits/6e451c965d400ab8eae79e1c2a1194eb1c0e6265#diff-6decbeed829df84146ae852633760d385978a82036f31bb91c2216ffdd60bf6fL217

I believe it shouldn't have been removed. Also, it should be more aptly called 'QUERY_DOMAINS' as it is a domain list.

**Comment by willbrowningme** [comment]
Okay, great work debugging. @crazy-max do you think the above needs adding back in as @slurdge mentions?

**Comment by willbrowningme** [comment]
@slurdge if you add those lines back in does the `check_access` stored procedure work as expected?

**Comment by slurdge** [comment]
I put the changes in a PR for review.
