### ISSUE TITLE
Postfix gives: "Operation timed out"

### ISSUE THREAD

**Issue by NVQXE23I** [anonaddy/docker#125]
I have installed this image and it all works, except for the one thing you need it for.. sending emails.
I have created a user (_via the "register"-button_), but the verification email with the link is **NOT** send because Postfix is looking at the wrong port?

My emailserver (the receiving one) is hosted by Transip in the Netherlands, which uses port 465 for SMTP.

In the logs of Postfix I see this:

```
anonaddy    | May 05 14:48:19 mail postfix/smtp[915]: connect to mx.transip.email[86.105.244.9]:25: Operation timed out
anonaddy    | May 05 14:48:49 mail postfix/smtp[915]: connect to relay.transip.nl[149.210.149.12]:25: Operation timed out
anonaddy    | May 05 14:49:19 mail postfix/smtp[915]: connect to relay.transip.nl[149.210.149.29]:25: Operation timed out
anonaddy    | May 05 14:49:19 mail postfix/smtp[915]: 60DC118FC2C: to=<myuser@mydomain.com>, relay=none, delay=90, delays=0.08/0.04/90/0, dsn=4.4.1, status=deferred (connect to relay.transip.nl[149.210.149.29]:25: Operation timed out)
```

Why is Postfix trying to deliver the email at port 25?

**Comment by willbrowningme** [comment]
Port 25 is used as the primary means of transmitting email between two mail servers. Looks like you may need to open it on your mail server to accept messages.

https://www.mailgun.com/blog/email/which-smtp-port-understanding-ports-25-465-587/
