### ISSUE TITLE
Anonaddy does not understand my custom SPF record

### ISSUE THREAD

**Issue by yurividal** [anonaddy/docker#129]
I have a custom domain added to my self-hosted anonaddy.
I had to change the SPF reccord from the default "v=spf1 mx -all" to something more specific, in order to pass gmail validations. I changed it to
````
v=spf1 a:myoriginaldomain.com a:myextradomain.xyz ipmypublicip include:proton.me include:_spf.google.com ~all
````
This passes all the spf validation in all tools i used. Anonaddy is able to send messages to this domain without any problems. It worked fine for a couple hours even though i hadn't reverified my domain records in anonaddy,. When the automatic re-validation ran, now anonaddy rejects outgoing messages, because it says the domain failed SPF validation. It is only accepting "v=spf1 mx -all"

![image](https://user-images.githubusercontent.com/8555749/173752604-79261438-2e80-4709-a5b0-0f1f83551ca9.png)

![image](https://user-images.githubusercontent.com/8555749/173752172-715aec0a-200e-45fa-9d85-5fbc46e683d8.png)

**Comment by willbrowningme** [comment]
Please could you try updating it to:

`v=spf1 mx a:myoriginaldomain.com a:myextradomain.xyz ipmypublicip include:proton.me include:_spf.google.com ~all`

that should work.

**Comment by yurividal** [comment]
Hi, i actually did something similar and ended up getting it to work. I did:
````
v=spf1 myoriginaldomain.com a:myoriginaldomain.com a:myextradomain.xyz mx:mail.myoriginaldomain.com ip4:mypublicip include:proton.me include:_spf.google.com ~all
````
Turns out this worked. Maybe, as improvement, the error message could be a bit more detailed.
