### ISSUE TITLE
Postfix gives: "Operation timed out"

### ISSUE THREAD

**Issue by NVQXE23I** [anonaddy/docker#136]
I have created a user (_via the "register"-button_), but the verification email with the link is **NOT** send because Postfix is looking at the wrong port?

My emailserver (the receiving one) is hosted by Anonaddy.me.

In the logs of Postfix I see this:

```
anonaddy    | Jun 23 14:08:02 mail postfix/smtp[975]: connect to mail.anonaddy.me[213.108.105.57]:25: Operation timed out
anonaddy    | Jun 23 14:09:19 mail postfix/smtp[915]: 7857B1AF493: to=<user@domain.com>, relay=none, delay=60, delays=0.06/0.01/60/0, dsn=4.4.1, status=deferred (connect to mail.anonaddy.me[213.108.105.57]:25: Operation timed out)
```

This issue is a follow-up for a closed issue. I have changed my mailserver to the one of anonaddy.me, but I kept on getting the same error.

**Comment by crazy-max** [comment]
@NVQXE23I Does not look linked to the Docker image but the online service.

@willbrowningme Can you transfer this issue to https://github.com/anonaddy/anonaddy.com? Maybe we should have a feedback repo for this like https://github.com/docker/hub-feedback? WDYT?

**Comment by willbrowningme** [comment]
@crazy-max or perhaps convert to a discussion?
@NVQXE23I so you are self-hosting the Docker image but you are using a custom domain that you've added to the hosted app.anonaddy.com service as your recipient address on the Docker image?

Port 25 is the correct port for communicating with the mail server.

**Comment by crazy-max** [comment]
@willbrowningme

> Port 25 is the correct port for communicating with the mail server.

Yeah looks like the hosting provider is blocking port 25.

@NVQXE23I Can you check outgoing is not blocked?

```
$ telnet mail.anonaddy.me 25
```

Closing this issue since that should answer your question, but feel free to re-open if it doesn't. Thanks.

**Comment by crazy-max** [comment]
@willbrowningme 

> or perhaps convert to a discussion?

Yes looks good too
