### ISSUE TITLE
Clarifications needed for Docker instalation and instance hardening

### ISSUE THREAD

**Issue by Malkorian** [anonaddy/docker#137]
Greetings, 

Considering, my limited experience with Dockers or Alpine, Could someone clarify a few questions about versions and hardening of the application and Docker file. 

What version of Alpine OS are we to use? 

Has ggshield been used to find any secrets/vulnerabilities in the docker file?  

Also, can someone enumerate the  daemons are required for Anonaddy to function, I'd like to fully utilize the brute force defense.    

Thanks and sorry about the deep dive,

**Comment by crazy-max** [comment]
> What version of Alpine OS are we to use?

Alpine 3.16: https://github.com/anonaddy/docker/blob/86ec3dee62ecc52035b337f29228a945b2825230/Dockerfile#L4

> Has ggshield been used to find any secrets/vulnerabilities in the docker file?

We directly fetch source code from upstream git repo https://github.com/anonaddy/anonaddy in https://github.com/anonaddy/docker/blob/86ec3dee62ecc52035b337f29228a945b2825230/Dockerfile#L89

> Also, can someone enumerate the daemons are required for Anonaddy to function, I'd like to fully utilize the brute force defense.

Just run the image and `top` inside the container

**Comment by Malkorian** [comment]
Thanks for replying, 
`
` FROM crazymax/alpine-s6:3.16-2.2.0.3 ``
Thanks for clarifying the Version 3.16; however, I was also concerned about the flavor.
 https://www.alpinelinux.org/downloads/ i.e. Standard vs Virtual vs Xen flavors.  
Since, the suggestions is to install the Anonaddy image on a VPS, Is the alpine version contingent on the hypervisor?  Considering some versions of Alpine work better on Xen, do the Alpine flavors work for all the type 2 hypervisors?  

So to resume, https://github.com/GitGuardian/ggshield has been used among other applications to secure Anonaddy?  

`Just run the image and top inside the container`  I might have some difficulty with this, so I'll follow up later.  Ultimately, the goal to make all the configurations on a testing server before deploying the anonaddy image on a live server.  

thanks,

**Comment by crazy-max** [comment]
> Is the alpine version contingent on the hypervisor? Considering some versions of Alpine work better on Xen, do the Alpine flavors work for all the type 2 hypervisors?

Not aware of any kind of issue but feel free to report if there is

> So to resume, https://github.com/GitGuardian/ggshield has been used among other applications to secure Anonaddy?

No
