### ISSUE TITLE
Unable to Update from v11 to v12

### ISSUE THREAD

**Issue by yurividal** [anonaddy/docker#142]
My container crashes when updating from v11 to v12. Is there an upgrade path?

GUI returns 
"500
SERVER ERROR"

**Comment by JasonHalvorson** [comment]
Having the same issue, enabling debug mode gives me this error:

> Could not get version string (`git describe` failed) (View: /var/www/anonaddy/resources/views/layouts/app.blade.php) (View: /var/www/anonaddy/resources/views/layouts/app.blade.php)

**Comment by willbrowningme** [comment]
If this is due to the GitVersionHelper class [here](https://github.com/anonaddy/anonaddy/blob/master/app/Helpers/GitVersionHelper.php#L66=) then I'll remove the Exception that is thrown there.

**Comment by willbrowningme** [comment]
I've just pushed a [new release](https://github.com/anonaddy/anonaddy/releases/tag/v0.12.3) that I hope will resolve this issue.

**Comment by yurividal** [comment]
> Please could you try again with the latest release [v0.12.3](https://github.com/anonaddy/docker/releases/tag/0.12.3-r0).

waiting for v0.12.3 to reach dockerhub

**Comment by yurividal** [comment]
> Please could you try again with the latest release [v0.12.3](https://github.com/anonaddy/docker/releases/tag/0.12.3-r0).

Confirmed 0.12.3 works fine. Thanks!
