### ISSUE TITLE
relay access denied 554 5.7.1 on 0.12.2/0.12.3 version . 

### ISSUE THREAD

**Issue by sakearzoo** [anonaddy/docker#145]
### Behaviour
After setting docker container with anonaddy version edge/latest/0.12.3/0.12.2. I am having error i,e Relay access denied 554. and email is not sending for verification. But when i downgrade the version of anonaddy to 0.11.2 everything works fine without error. It seems that with latest version 0.12.x it is facing error.
#### Steps to reproduce this issue
Setup a vm with ubuntu 20.04 lts 
1. create docker container anonaddy with version edge/latest/0.12.3/0.12.2. 
2. email will not go through and it will fail with error relay access denied.

#### Expected behaviour

> Verification email should go through without error

#### Actual behaviour

> Having error during register as email is not going through. error is:
Symfony\Component\Mailer\Exception\TransportException:
Expected response code "250/251/252" but got code "554", with message "554 5.7.1 <********@gmail.com>: Relay access denied".

### Configuration

* Docker version (type `docker --version`) :Docker version 20.10.17, build 100c701
* Docker compose version if applicable (type `docker-compose --version`) : Docker Compose version v2.2.2
* Platform (Debian 9, Ubuntu 18.04, ...) : ubuntu 20.04 LTS
* System info (type `uname -a`) : Linux containerr 5.11.0-1022 # 23 ~ 20.04.1-Ubuntu SMP Fri Nov 12 15:45:47 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...
docker-compose.yml

``````
version: "3.7"

services:
  db:
    image: mariadb:10.5
    container_name: anonaddy_db
    networks:
      - proxy2
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - "/home/ubuntu/anonaddy/db:/var/lib/mysql"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

    restart: always

  redis:
    image: redis:4.0-alpine
    container_name: anonaddy_redis
    restart: always
    networks:
      - proxy2

  anonaddy:
    image: anonaddy/anonaddy:latest
    container_name: anonaddy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy2 
    depends_on:
      - db
      - redis
    ports:
      - target: 25
        published: 25
        protocol: tcp
      - target: 465
        published: 465
        protocol: tcp
      - target: 587
        published: 587
        protocol: tcp
    volumes:
      - "/home/ubuntu/anonaddy/data:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy2"
      - "traefik.http.routers.anonaddy.tls=true"
      - "traefik.http.routers.anonaddy-secure.entrypoints=https"
      - "traefik.http.routers.anonaddy-secure.rule=Host(`****.****.cc`)"
      - "traefik.http.routers.anonaddy-secure.service=anonaddy"
      - "traefik.http.services.anonaddy.loadbalancer.server.port=8000"
    environment:
      - DB_HOST=db
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - REDIS_HOST=redis
      - TZ=Asia/Calcutta
      - PUID=1000
      - PGID=1000

      - MEMORY_LIMIT=512M
      - UPLOAD_MAX_SIZE=32M
      - OPCACHE_MEM_SIZE=256
      - REAL_IP_FROM=0.0.0.0/32
      - REAL_IP_HEADER=X-Forwarded-For
      - LOG_IP_VAR=http_x_forwarded_for

      - APP_KEY=base64:Wz************************************************vn5lIg=
      - APP_DEBUG=true
      - APP_URL=****.****.cc
      - ANONADDY_RETURN_PATH=******@****.cc
      - ANONADDY_ADMIN_USERNAME=narzoo
      - ANONADDY_ENABLE_REGISTRATION=true
      - ANONADDY_DOMAIN=****.cc
      - ANONADDY_ALL_DOMAINS=****.cc
      - ANONADDY_HOSTNAME=*******.****.cc
      - ANONADDY_DNS_RESOLVER=127.0.0.1
      - ANONADDY_SECRET=78V*****************************************Wrvn0=
      - ANONADDY_LIMIT=400
      - ANONADDY_BANDWIDTH_LIMIT=1048576000
      - ANONADDY_NEW_ALIAS_LIMIT=20
      - ANONADDY_ADDITIONAL_USERNAME_LIMIT=3
      - ANONADDY_DKIM_SIGNING_KEY=/data/dkim/****.cc.private
      - ANONADDY_DKIM_SELECTOR=default
      - LISTEN_IPV6=false
      - RSPAMD_ENABLE=true
      - RSPAMD_WEB_PASSWORD=******
      - MAIL_FROM_NAME=Sheikh-Nawab-Arzoo
      - MAIL_FROM_ADDRESS=****@****.cc
      - POSTFIX_DEBUG=false
      - POSTFIX_SMTPD_TLS=true
      - POSTFIX_SMTP_TLS=true
      - POSTFIX_SMTPD_TLS_CERT_FILE=/data/certs/****.cc/fullchain.pem
      - POSTFIX_SMTPD_TLS_KEY_FILE=/data/certs/****.cc/privkey.pem

networks:
  proxy2:
    external: true
``````

shared env:
````
MYSQL_DATABASE=anonaddy
MYSQL_USER=na******
MYSQL_PASSWORD=*****
````
### Docker info

```
> Output of command `docker info`
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)

Server:
 Containers: 20
  Running: 19
  Paused: 0
  Stopped: 1
 Images: 29
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c1**********************ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.11.0-1022
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 22.46GiB
 Name: containerr
 ID: ***********************************
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false


```

### Logs

```
> Container logs (set LOG_LEVEL to debug if applicable)

47.11.254.1 - - [16/Jul/2022:15:23:54 +0530] "GET /register HTTP/1.1" 200 1609 "https://****.****.cc/register" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
47.11.254.1 - - [16/Jul/2022:15:23:55 +0530] "GET /captcha/mini?FJDOdcep HTTP/1.1" 200 5329 "https://****.****.cc/register" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
crond: USER anonaddy pid 1244 cmd php /var/www/anonaddy/artisan schedule:run --no-ansi --no-interaction --quiet
47.11.254.1 - - [16/Jul/2022:15:24:15 +0530] "POST /register HTTP/1.1" 302 370 "https://****.****.cc/register" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
47.11.254.1 - - [16/Jul/2022:15:24:15 +0530] "GET /register HTTP/1.1" 200 1697 "https://****.****.cc/register" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
47.11.254.1 - - [16/Jul/2022:15:24:15 +0530] "GET /captcha/mini?nhVYb4i2 HTTP/1.1" 200 6811 "https://****.****.cc/register" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
Jul 16 15:24:24 **** postfix/smtpd[1251]: connect from localhost[127.0.0.1]
Jul 16 15:24:25 **** postfix/smtpd[1251]: Anonymous TLS connection established from localhost[127.0.0.1]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature RSA-PSS (4096 bits) server-digest SHA256
Jul 16 15:24:25 **** postfix/smtpd[1251]: NOQUEUE: reject: RCPT from localhost[127.0.0.1]: 554 5.7.1 <*****@gmail.com>: Relay access denied; from=<****@****.cc> to=<*****@gmail.com> proto=ESMTP helo=<[127.0.0.1]>
Jul 16 15:24:25 **** postfix/smtpd[1251]: using backwards-compatible default setting smtpd_relay_before_recipient_restrictions=no to reject recipient "*****@gmail.com" from client "localhost[127.0.0.1]"
47.11.254.1 - - [16/Jul/2022:15:24:25 +0530] "POST /register HTTP/1.1" 500 595735 "https://*****.****.cc/register" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
Jul 16 15:24:25 **** postfix/smtpd[1251]: disconnect from localhost[127.0.0.1] ehlo=2 starttls=1 mail=1 rcpt=0/1 rset=1 quit=1 commands=6/7

```

 DNS
`````


  | A | ***** | XXX.XXX.XXX.XX | DNS only | Auto | 
  | A | ********* | XXX.XXX.XXX.XX | DNS only | Auto | 
  | CNAME | * | redirect.******.******.cc | DNS only | Auto | 
  | MX | * | ****.****.cc | DNS only | Auto | 
  | MX | ****.cc | ****.****.cc | DNS only | Auto | 
  | TXT | ****.cc | v=spf1 mx ~all | DNS only | Auto | 
  | TXT | ****.cc | google-site-verification=**************************************| DNS only | Auto | 
  | TXT | default._domainkey | v=DKIM1; k=rsa; p=MIIB*************************************DAQAB | DNS only | Auto | 
  | TXT | _dmarc | v=DMARC1; p=reject; rua=mailto:*********@******.in; ruf=mailto:*********@******.in; sp=reject; fo=1; pct=100; aspf=r | DNS only | Auto | 
  | TXT | redirect.****** | v=spf1 mx ~all | DNS only | Auto | 



`````

**Comment by willbrowningme** [comment]
That looks to me like it is attempting to deliver the message to ***@gmail.com locally which is why it is returning relay access denied.

I think perhaps the following variables may need to be added to https://github.com/anonaddy/docker/blob/master/rootfs/etc/cont-init.d/00-env

```
MAIL_DRIVER=smtp
MAIL_HOST=mail.example.com
MAIL_PORT=25
MAIL_EHLO_DOMAIN=mail.example.com
MAIL_VERIFY_PEER=true
```

Not sure what port Docker uses for SMTP.

P.s. if that is your real Mysql username and password you should change it.

**Comment by sakearzoo** [comment]
> That looks to me like it is attempting to deliver the message to ***@gmail.com locally which is why it is returning relay access denied.
> 
> I think perhaps the following variables may need to be added to https://github.com/anonaddy/docker/blob/master/rootfs/etc/cont-init.d/00-env
> 
> ```
> MAIL_DRIVER=smtp
> MAIL_HOST=mail.example.com
> MAIL_PORT=25
> MAIL_EHLO_DOMAIN=mail.example.com
> MAIL_VERIFY_PEER=true
> ```
> 
> Not sure what port Docker uses for SMTP.
> 
> P.s. if that is your real Mysql username and password you should change it.



### That also didn't help still the same issue. 

HTTP 500 Internal Server Error

```
Port 465
Connection could not be established with host "ssl://*****.***.cc:465": stream_socket_client(): Unable to connect to ssl://*****.***.cc:465 (Connection refused)`


Port 587
Connection could not be established with host "*****.***.cc:587": stream_socket_client(): Unable to connect to *****.***.cc:587 (Connection refused)

Port 25
Expected response code "250/251/252" but got code "554", with message "554 5.7.1 <*******@gmail.com>: Relay access denied".
```

**Comment by yurividal** [comment]
I have the same issue after updating to 0.12.3
Rolling back to 0.11.2 solved the issue.

**Comment by willbrowningme** [comment]
If you add `smtpd_relay_before_recipient_restrictions=no` or `smtpd_relay_before_recipient_restrictions=yes` does it still show the same reject error in the logs?

**Comment by sakearzoo** [comment]
@willbrowningme changing yes to no and vice-versa does nothing. Still having relay access denied error with smtp.

**Comment by crazy-max** [comment]
Could this be linked to this change https://github.com/anonaddy/docker/pull/122 ?

**Comment by willbrowningme** [comment]
Possibly, definitely worth a try.

The only thing that has changed with v0.12.* vs v0.11.* is that the web application now uses Symfony mailer instead of Swift mailer, the SMTP settings should still work as they did previously.

**Comment by willbrowningme** [comment]
In the logs reported above the helo command seems to be `helo=<[127.0.0.1]>` which makes me think that `MAIL_EHLO_DOMAIN=mail.example.com` could be part of the problem. This needs to be added to the `.env` file since v0.12.*

Where `mail.example.com` is your server's hostname.

**Comment by willbrowningme** [comment]
Has anyone managed to test if this issue still persists when adding `permit_my_networks` back to `smtpd_recipient_restrictions` in `rootfs/etc/cont-int.d/15-config-postfix.sh` as below: 

```
smtpd_recipient_restrictions =
    permit_mynetworks,
    reject_unauth_destination,
    check_recipient_access mysql:/etc/postfix/mysql-recipient-access.cf,
    #check_policy_service unix:private/policyd-spf
    reject_rhsbl_helo dbl.spamhaus.org,
    reject_rhsbl_reverse_client dbl.spamhaus.org,
    reject_rhsbl_sender dbl.spamhaus.org,
    reject_rbl_client zen.spamhaus.org
    reject_rbl_client dul.dnsbl.sorbs.net
```

**Comment by ShawnTheShadow** [comment]
bit of testing with the MAIL_EHLO_DOMAIN env variable, seems it's ignored, still have the ``helo=<[127.0.0.1]>`` in the logs

**Comment by willbrowningme** [comment]
@ShawnTheShadow do you still have the same error with `permit_mynetworks` added as mentioned above?

**Comment by ShawnTheShadow** [comment]
When editing inside the container, and restarting, it gives a /data/storage already exists error and dies, have to recreate the container, i know that's going to be a different issue, it also happens on restart of the system
I'll see if i can spin up another instance using the git repo with the edits when i have more time

**Comment by sakearzoo** [comment]
today i checked the debug log and found that
```
match_list_match: smtpd_client_event_limit_exceptions: no match
match_list_match: hostname.mydomain.tld: no match
match_list_match: <public_ip>: no match
match_hostname: smtpd_client_event_limit_exceptions: hostname.mydomain.tld ~? 127.0.0.0/8
match_hostaddr: smtpd_client_event_limit_exceptions: <public_ip> ~? 127.0.0.0/8
```
neither hostname nor public ip matches.
i am unable to edit the container so if someone can try editing mynetworks list and add public ip / hostname to the list or adding both might solve the issue.

**Comment by willbrowningme** [comment]
@crazy-max PHP environment variables can be accessed via `$_ENV["FOO"]` - https://www.php.net/manual/en/reserved.variables.environment.php

But I don't know whether that would work as you mentioned or not.

**Comment by willbrowningme** [comment]
I do believe the issue is simply the missing `permit_my_networks` value for `smtpd_recipient_restrictions` as that is what the error seems to suggest.

**Comment by crazy-max** [comment]
> I do believe the issue is simply the missing `permit_my_networks` value for `smtpd_recipient_restrictions` as that is what the error seems to suggest.

Will revert that change and see how to improve injecting env vars in a follow-up

**Comment by crazy-max** [comment]
> PHP environment variables can be accessed via `$_ENV["FOO"]` - https://www.php.net/manual/en/reserved.variables.environment.php

Yes but Anonaddy doesn't read them currently right to override ones from `.env` file correct?

**Comment by willbrowningme** [comment]
That's right, it doesn't read them to override those in `.env`.

https://laravel.com/docs/9.x/configuration#retrieving-environment-configuration

When `php artisan config:cache` is run the web app caches the values for the `.env` values that are in the /config/* files.

https://laravel.com/docs/9.x/configuration#configuration-caching

**Comment by crazy-max** [comment]
Ok got it thanks!

**Comment by sakearzoo** [comment]
when i am using these env
``` 
MAIL_DRIVER=smtp
MAIL_HOST=mailer.mydomain.tld
MAIL_PORT=25
MAIL_EHLO_DOMAIN=mailer.mydomain.tld
MAIL_VERIFY_PEER=true
MAIL_ENCRYPTION=true
``` 
i am still getting relay access denied 
but removing this its working file and all mails reach into spam folder.

working log
``` 
match_list_match: smtpd_client_event_limit_exceptions: no match
match_list_match: localhost: no match
match_list_match: 127.0.0.1: no match
match_list_match: permit_mynetworks: no match
smtpd_acl_permit: smtpd_log_access_permit_actions: no match
```  

what should i do to get it fixed? as all mails dumps to spam folder. i have already set the records correctly and also validated through mxtoolbox and other online tools but i could not find the issue. 
any suggestion would be helpful. 


here are the complete logs:

1. relay access denied.log
https://pastebin.com/JFBphUDY
2. working.log
https://pastebin.com/Rdws8Mhs

**Comment by sakearzoo** [comment]
@willbrowningme 
most probably its not adding my public ip to mynetworks list while building the container. i am using portainer-ce for deploying this stack and my domain is behind traefik.

and can you suggest me how to add mta-sts and dane record to my docker container? 

i have added the latest log:
https://pastebin.com/FDwzZX7S

**Comment by crazy-max** [comment]
@sakearzoo 

> when i am using these env
> 
> ```
> MAIL_DRIVER=smtp
> MAIL_HOST=mailer.mydomain.tld
> MAIL_PORT=25
> MAIL_EHLO_DOMAIN=mailer.mydomain.tld
> MAIL_VERIFY_PEER=true
> MAIL_ENCRYPTION=true
> ```

You don't have to set them, they are populated automatically by the container in https://github.com/anonaddy/docker/blob/master/rootfs/etc/cont-init.d/13-config-anonaddy.sh

Valid env vars are on the README: https://github.com/anonaddy/docker#mail

**Comment by sakearzoo** [comment]
@crazy-max i have added those variable through environment variables directly on docker compose .
few things i have noticed that when i add `MAIL_VERIFY_PEER=true` the certificate doesn't match and getting error 
```Unable to connect with STARTTLS: stream_socket_enable_crypto(): Peer certificate CN=`4mc.cc' did not match expected CN=`127.0.0.1'```
if i  removing all those mail setting then it defaults to `localhost` and its able to establish tls connection and mail sent successfully. but certificate mismatches with more errors and mail reaches to spam folder. so i had to set all things which solves the certificate issue but mail isn't going through.

could you share your docker-compose.yml file so that i could try with my stack?

**Comment by crazy-max** [comment]
> i have added those variable through environment variables directly on docker compose .

these env vars will not be used by AnonAddy, see https://github.com/anonaddy/docker/issues/145#issuecomment-1189421582. if you want to inject arbitrary env vars see https://github.com/anonaddy/docker#define-additional-env-vars

**Comment by sakearzoo** [comment]
how to add mta-sts & dane records ? is it possible to add?

**Comment by sakearzoo** [comment]
@crazy-max 

> You can define additional environment variables that will be used by AnonAddy by creating a file named `.env` in `/data`.

i have tried creating .env file inside data folder but still seems to be ignored those files. 
for those do i have to mention at here 
```
   env_file:
      - "./anonaddy.env"
```
or is it automatically detected ?

**Comment by crazy-max** [comment]
no you have to create a file `./data/.env` and have `./data` bind mounted:

```yaml
    volumes:
      - "./data:/data"
```

but again you don't need to set these env vars. it should work as it is.

**Comment by sakearzoo** [comment]
Using docker-compose yml file

I have already mounted 

```
volumes:
      - "/home/ubuntu/anonaddy/data:/data"

```
And created a file locally at `/home/ubuntu/anonaddy/data/.env`


Even if I don't specify those variables and i am still able to send emails, I won't be able to figure out why my emails are being routed to the spam folder. I've already set up ptr records, dkim, dmarc, and spf. My emails continue to land in the spam bin. 


Even if I open ports- 587 , 465 i am unable to establish connection at those ports .

I am still confused about where i am going wrong .

**Comment by ShawnTheShadow** [comment]
What are the ARC headers and authentication results in the email's headers? (With all PII removed of course)

**Comment by crazy-max** [comment]
@sakearzoo 

> are being routed to the spam folder.

Maybe DMARC  misconfiguration or your IP is blacklisted. You can check at https://multirbl.valli.org/lookup/

**Comment by sakearzoo** [comment]
These are the details `Received: from [127.0.0.1] (localhost [127.0.0.1]) by mailer.mydomain.tld` where it should be from my hostname instead of localhost.

These are the arc details.

```

Delivered-To: myemail@gmail.com Received: by 2002:a0c:e751:0:0:0:0:0 with SMTP id g17csp1359610qvn; Wed, 20 Jul 2022 12:32:40 -0700 (PDT) X-Google-Smtp-Source: AGRyM1vfJcjDyLWKe/Xv/SS4c4PxmFcxXph8oHGBkTRkrF7YSx9CMyGokH5 X-Received: by 2002:a63:6404:0:b0:415:fa99:e287 with SMTP id y4-20020a636404000000b0041599e287mr34893pgb.220.1658345560263; Wed, 20 Jul 2022 12:32:40 -0700 (PDT) ARC-Seal: i=1; a=rsa-sha256; t=1658345560; cv=none; d=google.com; s=arc-20160816; b=h7VV6b3OI9aVcyewRygu4nYvT+TYI5kSWy4y4HuY9kO9NjmJ3IMrUwlLuk Umr/MVHuhgEPWhTW+2aIS6SccRlzW2IanYZ5TTCLxcyaL/9bhFMLLdZiaCXZvdn04 YrFLE/aQYgszXKMnyqmi0EG/1uaBupdeDd2wBsIREs5c934nIjvri3xph2ksfsw4x SX5k6tt4A4EkujLsCZWRcCOG+zUi8oVuRpYihWlsRu0JRaodF0ICyDq2X7pFQVl /9B9xQM6eF0aw/ahaL9t2RaHXnS62qpo9QkRVTkHo1yVcopZ8if03fTNNXHSIIFy0 aR0w== ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816; h=date:mime-version:message-id:feedback-id:subject:to:from :dkim-signature; bh=0Srto48xXp4PC6hga29KRfteZcTHADxYls=; b=Lw5hss5/an10n5WxXC3fUlvVY5D7DxGXtYnisfhzd7qHO4Om2V+49XWGf/ dO5l2n0DxLbu0b3ADYeguCUnIAxR1MVMU/OEiDPH8wif4OJlG1nsDQj/+QYrZ h4AabFqRMH8A+iR1w2+4ggmR0jeZPk22QdMAJnz9YTHzywm0f2mvdd/9bVqAFcL TWWFdHEt8v91Fk3Ag8sB264ugaftLv1ONbEJllnLhV3KGeP8AEwoTIeqNBGQ JFFFix7DXkDUQTsGvoze3wxHMlmAL8Fnb7ifdWojFfGqV718Merbx1ahjD9RCJ RUNg== ARC-Authentication-Results: i=1; mx.google.com; dkim=pass header.i=@mydomain.tld header.s=default header.b=GyHwMZLx; spf=pass (google.com: domain of mailer@mydomain.tld designates <publicip> as permitted sender) smtp.mailfrom=mailer@mydomain.tld; dmarc=pass (p=REJECT sp=REJECT dis=NONE) header.from=4mc.cc Return-Path: <mailer@mydomain.tld> Received: from mailer.mydomain.tld (mailer.mydomain.tld. [150.230.128.45]) by mx.google.com with ESMTPS id i71-20020a63a000000b004126e156abasi24441047pgd.142.2022.07.20.12.32.39 for <myemail@gmail.com> (version=TLS1_3 cipher=TLS_AES_256_GCM_SHA384 bits=256/256); Wed, 20 Jul 2022 12:32:40 -0700 (PDT) Received-SPF: pass (google.com: domain of mailer@mydomain.tld designates mypublicip as permitted sender) client-ip=mypublicip; Authentication-Results: mx.google.com; dkim=pass header.i=@4mc.cc header.s=default header.b=GyHwMZLx; spf=pass (google.com: domain of mailer@mydomain.tld designates mypublicip as permitted sender) smtp.mailfrom=mailer@mydomain.tld; dmarc=pass (p=REJECT sp=REJECT dis=NONE) header.from=4mc.cc Received: from [127.0.0.1] (localhost [127.0.0.1]) by mailer.mydomain.tld (Postfix) with ESMTPS id 9B08C390C for <myemail@gmail.com>; Thu, 21 Jul 2022 01:02:37 +0530 (IST) DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=4mc.cc; s=default; t=165834557; h=from:from:reply-to:subject:subject:date:date:message-id:message-id: 	 to:to:cc:mime-version:mime-version:content-type:content-type; bh=0SrtoyNQo48xXp4PC6h29KRftZDeZcTHADxYls=; b=GyHwMZLxTnz1h/q78tDtBDQJ14ugZ1Xm2T/d70NWw9VPmHCi47MkZZ5wNhaJoE 6GK4TE+O3QrD8WJ1rlYKywQ7uu+onTX8xKgSXKPml8rtUhqLNs10fd/0PNjJavH7u6H 5hZM2zmJc2tAXH2VZRIjbrkQdWn/xo9e+4c+qWzqa3JET9LAx/iUj4r4fBrz9urBiujub7 BgHn+TqDEsdgb7KdJz1kRF0Yvta3S5BlQLM1rsqYILgLY/tfvWlFNJS01/+3qLbCBXX yNx7V/yrIOM04nnIXpw/BkxYA9KwPxd9OO6Ag4JYhG2l2/SYpNBltg==

```

**Comment by ShawnTheShadow** [comment]
Looks like the DNS settings are all correct, check the blacklist check @crazy-max recommended, if you're doing it from home like from a nas, there are some blacklists that specifically block residental ip addresses

**Comment by ShawnTheShadow** [comment]
other than residential ip address blocking, only other thing i could think of would be poor ip/subnet reputation (which i had when i started my email server with dreamhost, took several months to improve it)

**Comment by ShawnTheShadow** [comment]
I've started using mailgun for my email proxy, it's free for the first 1000 emails for the month, there's several others out there

**Comment by sakearzoo** [comment]
@ShawnTheShadow do you have any idea how to setup mta-stsv1 & dane record with anonaddy docker container ?
