### ISSUE TITLE
recipients key note incorrect

### ISSUE THREAD

**Issue by youngt2** [anonaddy/docker#155]
I noticed that the note in the the 'key' under Recipients is incorrect.
![Screenshot 2022-07-29 143742](https://user-images.githubusercontent.com/5008078/181825071-84e3acdc-a072-4343-80f3-14401675227b.png)

It still references 'alias+key@user.anonaddy.com when it should really reference 'alias+key@mydomain.com', at least I would think it should for self-hosting.

**Comment by willbrowningme** [comment]
Thanks, will sort shortly.
