### ISSUE TITLE
Can't create aliases after upgrade from 0.12.3

### ISSUE THREAD

**Issue by tomtjes** [anonaddy/docker#165]
My installation was working well under with version 0.12.3. After upgrading to 0.13.x I can't create new aliases or rules: "An error has occurred, please try again later."
Downgrading to 0.12.3 restores functionality.
Any clues?

**Comment by Flash1232** [comment]
In fact there was a [closed issue](#163) that described what was happening. This is still the case but happened only after v0.13.4.

**Comment by tomtjes** [comment]
Thank you! Adding (as described [here](https://github.com/anonaddy/docker/issues/163#issuecomment-1222257628)) `SANCTUM_STATEFUL_DOMAINS=anonaddy.mydomain.com` to `data/.env` did the trick. I did not have to upgrade MariaDB to 10.8 as the OP of #163.

**Comment by crazy-max** [comment]
Found that strange since `SANCTUM_STATEFUL_DOMAINS` is set with `ANONADDY_DOMAIN` in https://github.com/anonaddy/docker/blob/6df1939c6d1ac9f3d3ee66db0c8875c3315b3d1a/rootfs/etc/cont-init.d/13-config-anonaddy.sh#L64

@tomtjes Is `ANONADDY_DOMAIN=anonaddy.mydomain.com` what you set?

**Comment by tomtjes** [comment]
Yes, perhaps it's because I use two different subdomains, as well as an additional domain:

```
ANONADDY_DOMAIN=mail.mydomain.com
ANONADDY_HOSTNAME=app.mydomain.com
ANONADDY_ALL_DOMAINS=mail.mydomain.com,my-other-domain.com
SANCTUM_STATEFUL_DOMAINS=app.mydomain.com,my-other-domain.com
```

**Comment by Flash1232** [comment]
> Thank you! Adding (as described [here](https://github.com/anonaddy/docker/issues/163#issuecomment-1222257628)) `SANCTUM_STATEFUL_DOMAINS=anonaddy.mydomain.com` to `data/.env` did the trick. I did not have to upgrade MariaDB to 10.8 as the OP of #163.

This seems to do the trick. I only use a single subdomain to access the web UI so I don't understand why this is necessary. There seems to be a breakage in one of the recent updates such that a 401 is thrown whenever a POST request is made.
