### ISSUE TITLE
postfix rejected legit email

### ISSUE THREAD

**Issue by yurividal** [anonaddy/docker#167]
Hi, i am expecting a legit email from a store. They say they have sent but i didnt get anything. Checking the logs, i see it was rejected by anonaddy:
````
Aug 21 09:15:15 anonaddy postfix/smtpd[1902]: NOQUEUE: reject: RCPT from mx2-eu2.digital.nuance.com[13.79.20.91]: 450 4.7.1 <smtp.digital.nuance.com>: Helo command rejected: Host not found; from=<no_reply@currys.co.uk> to=<CURRYS@MYDOMAIN.COM> proto=ESMTP helo=<smtp.digital.nuance.com>
````

I wonder if there is any way to allow this kind of messages through, as i missed an important email. (This was delivery instructions for an item i bought)

Seems like postfix, in the container has this:
````
smtpd_helo_restrictions =
    permit_mynetworks,
    permit_sasl_authenticated,
    reject_invalid_helo_hostname,
    reject_non_fqdn_helo_hostname,
    reject_unknown_helo_hostname
````

Maybe there could be an option to allow these messages?

**Comment by crazy-max** [comment]
You can now override postfix main configuration: https://github.com/anonaddy/docker#override-postfix-main-configuration

**Comment by Queuecumber** [comment]
Quick question about this: is there a decent case for removing `reject_unknown_helo_hostname`? 

It seems like it's fairly common for this check to fail (the server announcing itself as something which isn't public) for legitimate emails and I've seen a few issue requests about this (I also have this issue with university of maryland email servers). 

Furthermore simplelogin doesn't recommend using this option (https://github.com/simple-login/app#postfix). 

It would be nice not to have to include the entire `main.cf` just to remove that one line, is there a good argument for keeping it in?
