### ISSUE TITLE
Verification email sent from local docker install, 550 error from docker on server install, works local

### ISSUE THREAD

**Issue by klibansky** [anonaddy/docker#168]
### Behaviour

(Sorry for my title, perhaps a better title is appropriate?)

When I run AnonAddy from my MacBook pro via Docker Desktop with an arbitraty name as domain, a verification email is correctly being sent to a Gmail or icloud address and its correctly being received.

When I run the exact same Docker compose on my Synology rackstation (with or without a proper domain name setup), I get a ``550 Relay not permitted`` smtp error from the remote smtp server.

On both environments I use the exact same docker compose stack file.

#### Steps to reproduce this issue

1. Run docker compose stack file as seen below, same environment variables.
2. Log in to anonaddy and sent verification email
3. check logs

#### Expected behavior

Receive verification email.

#### Actual behavior

Get 550 error:
``Aug 21 01:25:26 forward postfix/smtp[1193]: EFB763DB3: to=<blabla@me.com>, relay=mx02.mail.icloud.com[17.56.9.19]:25, delay=1.4, delays=1.1/0.03/0.12/0.15, dsn=5.0.0, status=bounced (host mx02.mail.icloud.com[17.56.9.19] said: 550 Relay not permitted (in reply to RCPT TO command))``

### Configuration

Server (not working)
* Docker version (type `docker --version`) : `Docker version 20.10.3, build 55f0773`
* Docker compose version if applicable (type `docker-compose --version`) : `docker-compose version 1.28.5, build 24fb474e`
* Platform (Debian 9, Ubuntu 18.04, ...) : `Synology 7.1-42661 Update 4`
* System info (type `uname -a`) : `Linux Server02 3.10.108 #42661 SMP Mon Jun 27 15:06:18 CST 2022 x86_64 GNU/Linux synology_bromolow_rs18016xs+`

Local (working)
* Docker version (type `docker --version`) : `Docker version 20.10.17, build 100c701`
* Docker compose version if applicable (type `docker-compose --version`) : `docker-compose version 1.29.2, build 5becea4c`
* Platform (Debian 9, Ubuntu 18.04, ...) : `MacOS 12.5`
* System info (type `uname -a`) : `Darwin HostName.local 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000 arm64`

### Logs

Local instance
```
Aug 21 16:39:38 forward postfix/smtpd[1341]: connect from localhost[127.0.0.1]

Aug 21 16:39:38 forward postfix/smtpd[1341]: CF8342C1BC4: client=localhost[127.0.0.1]

Aug 21 16:39:38 forward postfix/cleanup[1344]: CF8342C1BC4: message-id=<e1f92a0b205caddb1b020120d59fa76b@localhost.com>

Aug 21 16:39:38 forward postfix/qmgr[1034]: CF8342C1BC4: from=<noreply@localhost.com>, size=14162, nrcpt=1 (queue active)

Aug 21 16:39:38 forward postfix/smtpd[1341]: disconnect from localhost[127.0.0.1] ehlo=1 mail=1 rcpt=1 data=1 quit=1 commands=5

Aug 21 16:39:43 forward postfix/smtp[1345]: CF8342C1BC4: to=<test@me.com>, relay=mx01.mail.icloud.com[17.42.251.10]:25, delay=5.1, delays=0.01/0/2.2/2.9, dsn=2.0.0, status=sent (250 2.0.0 Ok: queued as 11DE1BA37D1)

Aug 21 16:39:43 forward postfix/qmgr[1034]: CF8342C1BC4: removed
```

Synology (production) instance
```
Aug 21 16:42:32 forward postfix/smtpd[7789]: connect from localhost[127.0.0.1]

Aug 21 16:42:33 forward postfix/smtpd[7789]: 1AFAC4507: client=localhost[127.0.0.1]

Aug 21 16:42:33 forward postfix/cleanup[7792]: 1AFAC4507: message-id=<045a543a5377a43195fbc2cc184adab5@production.com>

Aug 21 16:42:35 forward postfix/qmgr[1157]: 1AFAC4507: from=<noreply@production.com>, size=14307, nrcpt=1 (queue active)

Aug 21 16:42:35 forward postfix/smtpd[7789]: disconnect from localhost[127.0.0.1] ehlo=1 mail=1 rcpt=1 data=1 quit=1 commands=5

Aug 21 16:42:35 forward postfix/smtp[7793]: 1AFAC4507: to=<testemail@me.com>, relay=mx01.mail.icloud.com[17.57.156.24]:25, delay=2.3, delays=2/0.06/0.13/0.06, dsn=5.0.0, status=bounced (host mx01.mail.icloud.com[17.57.156.24] said: 550 Relay not permitted (in reply to RCPT TO command))

Aug 21 16:42:35 forward postfix/smtp[7793]: 1AFAC4507: lost connection with mx01.mail.icloud.com[17.57.156.24] while sending DATA command

Aug 21 16:42:35 forward postfix/cleanup[7792]: 421854515: message-id=<20220821144235.421854515@forward.production.com>

Aug 21 16:42:35 forward postfix/bounce[7794]: 1AFAC4507: sender non-delivery notification: 421854515

Aug 21 16:42:35 forward postfix/qmgr[1157]: 421854515: from=<>, size=16955, nrcpt=1 (queue active)

Aug 21 16:42:35 forward postfix/qmgr[1157]: 1AFAC4507: removed

Aug 21 16:42:36 forward postfix/pipe[7795]: 421854515: to=<noreply@production.com>, relay=anonaddy, delay=0.98, delays=0.08/0.03/0/0.87, dsn=2.0.0, status=sent (delivered via anonaddy service)

Aug 21 16:42:36 forward postfix/qmgr[1157]: 421854515: removed
```

### anonaddy.env
```
TZ=Europe/Amsterdam
PUID=1000
PGID=1000

MEMORY_LIMIT=512M
UPLOAD_MAX_SIZE=50M
OPCACHE_MEM_SIZE=128
REAL_IP_FROM=0.0.0.0/32
REAL_IP_HEADER=X-Forwarded-For
LOG_IP_VAR=http_x_forwarded_for

APP_KEY=*****
APP_DEBUG=true
APP_URL=http://forward.domain.com:8111

ANONADDY_RETURN_PATH=bounces@domain.com
#ANONADDY_ADMIN_USERNAME=anonaddy
ANONADDY_ENABLE_REGISTRATION=false
ANONADDY_DOMAIN=domain.com
ANONADDY_ALL_DOMAINS=domain.com
ANONADDY_HOSTNAME=forward.domain.com
ANONADDY_DNS_RESOLVER=1.1.1.1
ANONADDY_SECRET=******
ANONADDY_LIMIT=200
ANONADDY_BANDWIDTH_LIMIT=10737418240
ANONADDY_NEW_ALIAS_LIMIT=10
ANONADDY_ADDITIONAL_USERNAME_LIMIT=10
ANONADDY_WORDLIST_FILE=/var/www/anonaddy/config/wordlist.json

SANCTUM_STATEFUL_DOMAINS=localhost,localhost:8111,127.0.0.1,127.0.0.1:8111,::1,0.0.0.0,0.0.0.0:8111,forward.domain.com,forward.domain.com:8111

MAIL_FROM_NAME=randompete
MAIL_FROM_ADDRESS=noreply@domain.com

POSTFIX_DEBUG=false
POSTFIX_SMTPD_TLS=false
POSTFIX_SMTP_TLS=false
POSTFIX_SMTPD_TLS_CERT_FILE=/certs/certificate.pem
POSTFIX_SMTPD_TLS_KEY_FILE=/certs/privatekey.pem

#DKIM_ENABLE=true
#DMARC_ENABLE=true

RSPAMD_ENABLE=true
RSPAMD_WEB_PASSWORD=abc
```

### docker compose
```
version: "3.5"

services:
  anonaddy_db:
    image: mariadb:10.8
    container_name: anonaddy_db
    ports:
      - target: 3306
        published: 55009
        protocol: tcp
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - "/Users/***/Documents/docker/anonaddy/db:/var/lib/mysql"
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE"
      - "MYSQL_USER"
      - "MYSQL_PASSWORD"
    restart: always

  anonaddy_redis:
    image: redis:latest
    container_name: anonaddy_redis
    restart: always

  anonaddy:
    image: anonaddy/anonaddy:latest
    container_name: anonaddy
    depends_on:
      - anonaddy_db
      - anonaddy_redis
    ports:
      - target: 25
        published: 25
        protocol: tcp
      - target: 8000
        published: 8111
        protocol: tcp
      - target: 11334
        published: 11334
        protocol: tcp

    volumes:
      - "/Users/***/Documents/docker/anonaddy/data:/data"
    env_file:
      - "./anonaddy.env"
    environment:
      - "DB_HOST=anonaddy_db"
      - "DB_DATABASE=${MYSQL_DATABASE}"
      - "DB_USERNAME=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "REDIS_HOST=anonaddy_redis"
    restart: always
```

**Comment by klibansky** [comment]
Could this be due to the version difference of docker?

**Comment by yurividal** [comment]
check the version of docker-compose on both your systems. Old docker-compose can sometimes mess a lot of things up, especially when it comes to networking. 
````
docker-compose -v
````

even better, if you ca update your docker and use "docker compose" instead of "docker-compose". (yes, its different)

**Comment by klibansky** [comment]
Yes check out my versions in the configuration section of my original post. Unfortunately Synology has an outdated version... they will update next year. Stupid i know. 
Might there be a specific launch option that i can use or a network setting to mitigate the issue on the older version?

**Comment by klibansky** [comment]
I want to close this issue because I have AnonAddy fully functional on a proper internet facing server (a VPS via Hetzner) so I attribute this issue to the way Synology implement a Dorker and perhaps the older version of it or its network implementation.
