### ISSUE TITLE
Unable to reply back to forwarded email

### ISSUE THREAD

**Issue by bingh0** [anonaddy/docker#169]
Hello, running Anonaddy 0.13.5 armv7 alpine docker image using docker-compose. dkim configured. Not running rspamd or GPG. Other than my custom domain name, pretty much every other environment variable is default. Emails forward properly, but replies fail with below anonaddy generated email error (from gmail in this instance). Have tried multiple different email providers.

An attempt to send or reply from your alias [] was just made from [] which failed because it didn't pass authentication checks and could be a spoofed.

In order to send or reply from an alias there must be a valid DMARC policy present for [gmail.com](http://gmail.com/) and your message must be permitted by that DMARC policy.

The attempt was trying to send the message to the following destination: []

If this attempt was made by yourself, then you need to make sure your recipient's domain ([gmail.com](http://gmail.com/)) has the correct DNS records in place; SPF, DKIM and DMARC.

If this attempt was not made by you, then someone else may be attempting to send a message from your alias. Make sure you have a suitable DMARC policy in place (with p=quarantine or p=reject) along with SPF and DKIM records to protect your recipient's email address from being spoofed.

**Comment by willbrowningme** [comment]
The problem might be that you are not running Rspamd, as it is Rspamd that adds the `X-AnonAddy-Dmarc-Allow` header:

https://github.com/anonaddy/docker/blob/master/rootfs/etc/cont-init.d/14-config-rspamd.sh#L134-L151

Without that header you will get the message as above, since your recipient must explicitly pass DMARC checks in order to be able to send/reply from aliases.

Please try adding Rspamd and see if that resolves it.

**Comment by klibansky** [comment]
I do have Rspamd enabled and running but I'm also getting the same (bounce) mail and not able to reply.
Is there a way I can debug/check that I have setup everything correctly? (I think I have).
Enabled Rspamd in docker .env file. 
Generated Dkim and added to txt records + all other txt records.

**Comment by luckydonald** [comment]
> The problem might be that you are not running Rspamd, as it is Rspamd that adds the X-AnonAddy-Dmarc-Allow header:

Oh wow.

That look me days trying to get that working. And in the end it was a completely unrelated setting.

**Comment by luckydonald** [comment]
Btw, permanent link to the code line you mentioned is:

[ https://github.com/anonaddy/docker/blob/4d6740ed81c070685c7ec3f39e65ee26f108db07/rootfs/etc/cont-init.d/14-config-rspamd.sh#L134-L151](https://github.com/anonaddy/docker/blob/4d6740ed81c070685c7ec3f39e65ee26f108db07/rootfs/etc/cont-init.d/14-config-rspamd.sh#L134-L151)

You can easily press <kbd>Y</kbd> on a code page to get a link including the commit hash, and as such always pointing to the relevant section, even years later.
