### ISSUE TITLE
Bounced email with php error with extra domain name

### ISSUE THREAD

**Issue by klibansky** [anonaddy/docker#170]
### Behaviour

In the web UI, after adding another domain and adding the DNS records; when I send an email to the new domain name alias, I get a bounce mail (and error log) with the following: 
```
postfix/pipe[1014]: C868C7F15B: to=<if1xvmxh@extra-domain.com>, relay=anonaddy, delay=2.1, delays=0.7/0.01/0/1.4, dsn=5.3.0, status=bounced
Command died with status 1: "php". Command output:  In DkimSigner.php line 42: Symfony\Component\Mime\Crypto\DkimSigner::__construct(): Argument #1 ($pk) must be of type string, null given, called in /var/www/anonaddy/app/CustomMailDriver/CustomMailer.php on line 92
```

#### Steps to reproduce this issue

1. Setup AnonAddy via docker image
2. Add another domain name via web UI
3. Also tried to add the extra domain name via docker .env file

#### Expected behaviour

Receive email on new alias+domain name

#### Actual behaviour

Email bounced with error message:
```
This is the mail system at host email.domain.com.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                  The mail system

<if1xvmxh@extra-domain.com>: Command died with status 1: "php". Command output:  In
   DkimSigner.php line 42:
   Symfony\Component\Mime\Crypto\DkimSigner::__construct(): Argument #1 ($pk)
   must be of type string, null given, called in /var/www/anonaddy/app/CustomM
   ailDriver/CustomMailer.php on line 92
Reporting-MTA: dns; email.domain.com
X-Postfix-Queue-ID: C868C7F15B
X-Postfix-Sender: rfc822; sender-test-email@icloud.com
Arrival-Date: Wed, 31 Aug 2022 16:56:05 +0200 (CEST)

Final-Recipient: rfc822; if1xvmxh@extra-domain.com
Original-Recipient: rfc822;if1xvmxh@extra-domain.com
Action: failed
Status: 5.3.0
Diagnostic-Code: x-unix; In DkimSigner.php line 42:
   Symfony\Component\Mime\Crypto\DkimSigner::__construct(): Argument #1 ($pk)
   must be of type string, null given, called in /var/www/anonaddy/app/CustomM
   ailDriver/CustomMailer.php on line 92
```

**Comment by qcasey** [comment]
Did you ever find a solution to this? I'm seeing the same issue

**Comment by qcasey** [comment]
Nevermind, as per the error message it wants a DKIM key for `email.domain.com`.

1. Create DKIM keypair as [per these instructions](https://github.com/anonaddy/docker#generate-dkim-privatepublic-keypair).
2. Add the [env variable](https://github.com/anonaddy/docker#anonaddy) to `anonaddy.env`, it'll probably look like `ANONADDY_DKIM_SIGNING_KEY=/data/dkim/email.domain.com.private`

**Comment by klibansky** [comment]
Thanks so much. I have been battling and learning a lot about DKIM, DMARC and SPF in order to get it to work. 
I must say it's not particularly well documented in a way that you can set it up in one go (there are some gaps) but I now have AnonAddy fully functional (with all it's features [replying to alias and email address with subdomain + adding other domain names]).
