### ISSUE TITLE
ANONADDY_ALL_DOMAINS?

### ISSUE THREAD

**Issue by dahamsta** [anonaddy/docker#172]
Do I need to add domains I want to use here as well as in AnonAddy? Sorry, it's not clear from the docs.

**Comment by crazy-max** [comment]
See https://github.com/anonaddy/anonaddy/blob/1c00d056f1c875d4d991d32f6400c0dd9896b2bf/config/anonaddy.php#L87-L97, will update README to link to this config to have more details.

**Comment by crazy-max** [comment]
Updated in https://github.com/anonaddy/docker/commit/268f83cf614cc52fcfda18737324bcda544ac607

**Comment by dahamsta** [comment]
Thanks for editing the documentation, however it's still not clear that the domains also need to be added in AnonAddy, perhaps this should be noted also? Out of curiosity, why does it need to be added in both?

**Comment by dahamsta** [comment]
Ah, I see, thanks very much for the explanation. Is it possible to disable the catch-all on "local" domains, or can this only be done for per-user domains? Are there any other differences between the two?

**Comment by willbrowningme** [comment]
Catch-all should work for `ANONADDY_ALL_DOMAINS` if you've added your username for `ANONADDY_ADMIN_USERNAME` e.g.

```
ANONADDY_ADMIN_USERNAME=johndoe
```

**Comment by willbrowningme** [comment]
No other major differences apart from you have a few more options when adding as a custom domain from the domains page.

**Comment by dahamsta** [comment]
> Catch-all should work for `ANONADDY_ALL_DOMAINS` if you've added your username for `ANONADDY_ADMIN_USERNAME` e.g.

I was more wondering if it was possible to **disable** the catch-all for a local domain, without losing access to the top-level of the domain.

> No other major differences apart from you have a few more options when adding as a custom domain from the domains page.

Thanks.

**Comment by willbrowningme** [comment]
If you want to fully disable catch-all for a domain in `ANONADDY_ALL_DOMAINS` then you need to update `/etc/postfix/mysql-recipient-access.cf` like this:

After line [239](https://github.com/anonaddy/docker/blob/master/rootfs/etc/cont-init.d/15-config-postfix.sh#L239) update it to:

```sql
# Check if the alias uses a shared domain and does not exist, if so reject
IF no_alias_exists AND alias_domain IN('yourdomain.com', 'yourdomain2.com') THEN
    SELECT 'REJECT Address does not exist';
ELSE
    # If there is an alias, check if it is deactivated or deleted
    IF NOT no_alias_exists THEN
    ...
    ...
    ...
    # If all actions are NULL then we can return 'DUNNO' which will prevent Postfix from trying substrings of the alias
        IF username_action IS NULL AND domain_action IS NULL THEN
            SELECT 'DUNNO';
        ELSEIF username_action IN('DISCARD','REJECT Address does not exist') THEN
            SELECT username_action;
        ELSE
            SELECT domain_action;
        END IF;
    END IF;
END IF;
```

So you are just placing the existing lines [241-300](https://github.com/anonaddy/docker/blob/master/rootfs/etc/cont-init.d/15-config-postfix.sh#L241-L300) inside the `ELSE` statement we added above.

This will then reject and messages sent to your domain that do not already exist.

**Comment by dahamsta** [comment]
Nice, thanks. I don't want to do this right now, but I imagine it would be useful if a domain is dictionary-attacked, which has happened to me in the past. As an alternative to the hack, perhaps local domains could be added to the Domains page, albeit undeletable, or alternatively a flag added to the env file to automate it.

I've just though of another question, sorry! I don't use username.domain hostname at all, only the top-level domain, is it possible to disable that so it doesn't appear in the UI? I realise these are all self-hosted questions, sorry again. :)

**Comment by willbrowningme** [comment]
Adding a .env flag would probably be easiest for me to add for that. I agree though it would be nice to see the shared domains on the self-hosted version (but just not be able to delete them) and only from the admin account.

To be honest I haven't made any self-hosting specific changes so it is essentially the same as the hosted version. When I get time I'll try to make some improvements to it for people who don't need the username subdomains etc.

**Comment by dahamsta** [comment]
Yes, from a usability pov, showing them on the Domains page would be good. Neither of these are urgent, just thoughts, thanks for taking the feedback. :)
