### ISSUE TITLE
`spamhaus.org; Error: open resolver;` preventing me from sending or receiving emails

### ISSUE THREAD

**Issue by necropolina** [anonaddy/docker#182]
My instance has been working fine for ~8 months, but I suddenly started seeing this recently when I attempt to send/receive emails. I know the `Setting up a local caching DNS resolver` section in the [self hosting guide](https://anonaddy.com/self-hosting/) is relevant here, but I would've thought that the docker container handled that (my env does have `ANONADDY_DNS_RESOLVER=127.0.0.1` per the docker guidelines) - and that section seems targeted to people doing manual installs.

I also had DKIM set up rather than Rspamd, and I noticed that DKIM was deprecated while looking into the open resolver issue. I removed the DKIM configs but haven't set Rspamd up yet. Would this issue be caused by Rspamd not being set up yet?

**Comment by KevinRoebert** [comment]
Spamhaus does enforce more and more blocking of open resolvers like 8.8.8.8 or 1.1.1.1

You can setup [Spamhaus DQL](https://github.com/anonaddy/docker#spamhaus-dqs-configuration) as the "offical" way to query spamhaus.

**Comment by necropolina** [comment]
Followed the advice in that section and added the DQS query key as `POSTFIX_SPAMHAUS_DQS_KEY` in my .env, but still seeing the open resolver issue. Is there something else I might be missing?

**Comment by KevinRoebert** [comment]
The feature was added to the latest version. Are you using the latest version?

**Comment by necropolina** [comment]
Ah, thought I was but apparently I wasn't. :P Working now, thanks so much!
