### ISSUE TITLE
Update anonaddy

### ISSUE THREAD

**Issue by ririko5834** [anonaddy/docker#190]
How do I update anonaddy that is hosted using docker.
I have pulled the image and reacreated the container but its still showing the older version on anonaddy website footer
![image](https://user-images.githubusercontent.com/64729293/198554567-20ab44dd-1ce6-4ee8-aa02-09d1d81c7a80.png)

**Comment by ririko5834** [comment]
The latest is v0.13.9

**Comment by ririko5834** [comment]
![image](https://user-images.githubusercontent.com/64729293/198554969-33b90288-f10b-4ebb-9a8d-b084ba317062.png)
![image](https://user-images.githubusercontent.com/64729293/198555118-5d4314be-8b3a-49b5-8ced-ea3a0c8c642c.png)

**Comment by crazy-max** [comment]
> How do I update anonaddy that is hosted using docker.

https://github.com/anonaddy/docker#upgrade

> I have pulled the image and reacreated the container but its still showing the older version on anonaddy website footer

That looks good to me:

```console
$ docker buildx imagetools inspect anonaddy/anonaddy:latest --format '{{json (index .Image "linux/amd64")}}' | jq .config.Labels
{
  "org.opencontainers.image.created": "2022-10-18T07:50:43.152Z",
  "org.opencontainers.image.description": "Anonymous Email Forwarding",
  "org.opencontainers.image.licenses": "MIT",
  "org.opencontainers.image.revision": "aac8ad22f7a1960eae0ef6f597928a4adc6279b8",
  "org.opencontainers.image.source": "https://github.com/anonaddy/docker",
  "org.opencontainers.image.title": "AnonAddy",
  "org.opencontainers.image.url": "https://github.com/anonaddy/docker",
  "org.opencontainers.image.vendor": "CrazyMax",
  "org.opencontainers.image.version": "0.13.9"
}
```

Looks like you're using Portainer, you should ask their: https://github.com/portainer/portainer

**Comment by ririko5834** [comment]
> You can upgrade AnonAddy automatically through the UI, it works well.

Where can I do it?
