### ISSUE TITLE
/var/www/anonaddy has wrong UID/GID if different from 1000

### ISSUE THREAD

**Issue by slurdge** [anonaddy/docker#20]
I  think the script fix_perms should also set anonaddy user as the owner of /var/www/anonaddy.
For example, the config folder is not writable if the UID/GID is different from 1000.

**Comment by crazy-max** [comment]
@slurdge Actually, `/var/www/anonaddy` should be owned by `nobody.nogroup`. Only `/data` and nginx related folders should be owned by `anonaddy` user. I will update the Docker image to reflect that.

**Comment by slurdge** [comment]
Wouldn't it cause problems with the bootstrap & config folders? My errors were coming from that.

**Comment by crazy-max** [comment]
@slurdge Have you checked the [Volumes section](https://github.com/anonaddy/docker#volumes) in the README about ownership?
