### ISSUE TITLE
If used with PUID=1001 and GUID=1001, the scripts fail to start

### ISSUE THREAD

**Issue by slurdge** [anonaddy/docker#21]
#### Steps to reproduce this issue

1. Use the docker-compose file
2. Change the PUID & GUID to 1001
3. Execute docker-compose logs:

```
anonaddy    |   file_put_contents(/var/www/anonaddy/bootstrap/cache/config.php): failed to   
anonaddy    |   open stream: Permission denied                                               

anonaddy    |   copy(/var/www/anonaddy/config/trustedproxy.php): failed to open stream: Per  
anonaddy    |   mission denied                                                               
```

#### Expected behaviour

Instance should start

### Configuration

* Docker version (type `docker --version`) : Docker version 19.03.5, build 633a0ea838
* Docker compose version if applicable (type `docker-compose --version`) : docker-compose version 1.23.2, build 1110ad01
* Platform (Debian 9, Ubuntu 18.04, ...) : Debian 9
* System info (type `uname -a`) : Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

**Comment by slurdge** [comment]
If I change back to 1000&1000, it works (every time I erase /data & /db).
If I docker exec and chown {bootstrap, config} to 1001&1001 it works too.

**Comment by crazy-max** [comment]
@slurdge Looks like a bug yes. Thanks for your input. Stick to `1000:1000` for now.

**Comment by crazy-max** [comment]
@slurdge Should be fixed now!
