### ISSUE TITLE
How to Generate DKIM private/public keypair when hosting on portainer

### ISSUE THREAD

**Issue by ririko5834** [anonaddy/docker#222]
Hi, I host anonaddy as stack on portainer, how do I Generate DKIM private/public keypair? I am changing domain so I am also wondering if its needed to regenerate key, and what is the key good for (I guess for DKIM record for adding custom domains)? Is it needed? I don't have PGP encryption turned on.
When I do exec and run the cmd, it doesn't work
![image](https://github.com/anonaddy/docker/assets/64729293/6838b6af-857b-4dba-a39c-4096f211a217)

When I tried to exec cmd as anonaddy user
![image](https://github.com/anonaddy/docker/assets/64729293/6ae7d2ab-69a8-468c-86cf-e657fa021fb9)

**Comment by crazy-max** [comment]
It's not an `artisan` command but a dedicated script. Just call `gen-dkim`.

**Comment by ririko5834** [comment]
thanks
