### ISSUE TITLE
Update to latest version after rebranding to addy

### ISSUE THREAD

**Issue by ririko5834** [anonaddy/docker#226]
Update this docker image to the latest version of addy.io.Many things changed after rebranding, we will have to wait until Will updates the github repo, I already emailed him 
![image](https://github.com/anonaddy/docker/assets/64729293/2a6a696a-c555-4a69-8b2b-cabcec57c018)

**Comment by crazy-max** [comment]
> Update this docker image to the latest version

Not sure what you mean, we are already at the latest version: https://github.com/anonaddy/anonaddy/releases/tag/v0.14.1

**Comment by willbrowningme** [comment]
It will be updated next month.
