### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by Git-Cluster** [anonaddy/docker#23]
I am getting this error after installation.

**Comment by crazy-max** [comment]
@Git-Cluster https://github.com/anonaddy/docker/blob/master/.github/SUPPORT.md#reporting-an-issue

**Comment by honestlai** [comment]
I am also getting this, I don't know what steps I need to follow for doing a docker install, there doesn't seem to be any instructions anywhere. I did fill out the .env file, but when I load the site I get a "500 | Server Error"
