### ISSUE TITLE
Update to v1.x

### ISSUE THREAD

**Issue by yurividal** [anonaddy/docker#239]
### Description

Hi. Will this image need to be adapted to work with anonaddy 1.x + ?
Are there plans of doing so?

**Comment by crazy-max** [comment]
Yes I will work on it, keep you posted.

**Comment by rehanone** [comment]
@crazy-max , is there any update on this?

**Comment by crazy-max** [comment]
Yes opened #240, I'm looking at the branding to check if everything is aligned. Will mark for review asap.

**Comment by rehanone** [comment]
@crazy-max , Please merge #240 as it looks like @willbrowningme has approved it.

**Comment by anondev-sudo** [comment]
Can you update it to the latest version after rebranding to Addy.io?
If I then just pull the image will it work or do I need to migrate it somehow. I don't want to lose all my aliases and other stuff

**Comment by yurividal** [comment]
@crazy-max  seems like your 1.0.4 image doesn't include the breaking changes of addy.io 1.0.0 , specifically the one regarding main.cf that needs to be updated.
For now, i have mounted a fixed version of this file, but it needs to be fixed in your image.
