### ISSUE TITLE
Update on portainer

### ISSUE THREAD

**Issue by ririko5834** [anonaddy/docker#246]
How do I update it on portainer to the latest rebranded addyio version?
![image](https://github.com/anonaddy/docker/assets/64729293/f35bca09-f252-4814-8f8e-7c6d45666e7e)
![image](https://github.com/anonaddy/docker/assets/64729293/423b8d69-457c-4aac-9fa5-d5bca07b3db9)

**Comment by crazy-max** [comment]
Not yet released: https://github.com/anonaddy/docker/releases

**Comment by ririko5834** [comment]
when it will be released

**Comment by ririko5834** [comment]
I have pulled from edge tag and it works fine, didn't have to change anything or do some migrations

**Comment by crazy-max** [comment]
I'm looking at updating Alpine to 3.19 and also update addy to 1.0.4
