### ISSUE TITLE
[Improvement] Add a feature to see created users.

### ISSUE THREAD

**Issue by slurdge** [anonaddy/docker#26]
It is useful to see how many/when users are created.

Right now I have this script:
```bash
set -a
[ -f .env ] && . .env
set +a
docker-compose exec anonaddy mysql --host db --database $MYSQL_DATABASE --user $MYSQL_USER -p$MYSQL_PASSWORD -e "select id, username, created_at, updated_at from users;"
```

which does the job, but we could integrate it directly into the docker image in order to have a command like
`docker-compose exec anonaddy get_users`

My docker-fu is a bit lacking, but if pointed in to the right direction I can try a PR.

**Comment by crazy-max** [comment]
I think it would be better to implement this through artisan on the main repo. WDYT @willbrowningme ?

**Comment by willbrowningme** [comment]
Yes, I can add an artisan command to display the current users. I'll update it shortly.

**Comment by willbrowningme** [comment]
Added in latest release - https://github.com/anonaddy/anonaddy/releases/tag/v0.2.13 as `php artisan anonaddy:list-users`
