### ISSUE TITLE
Emails not sent in 0.6.0

### ISSUE THREAD

**Issue by djedje72** [anonaddy/docker#29]
### Behaviour
Email are not sent. It's ok with the same docker configuration with 0.5.0 but KO in 0.6.0.
#### Steps to reproduce this issue

1. Register a new account or validate a new recipient
2. Send the verification email

#### Expected behaviour

> should receive the email in mailbox

#### Actual behaviour

> no postfix error, but no email.

**Comment by willbrowningme** [comment]
Hard to debug this without further details. Are there are errors shown in the Laravel log files? Does the mail.log show that the verification email is delivered?

**Comment by djedje72** [comment]
Hello, where can i find the requested logs ?

Docker logs 0.5.0 : [AnonAddy_0_5_0.txt](https://github.com/anonaddy/docker/files/5433810/AnonAddy_0_5_0.txt)
Docker logs 0.6.0 : [AnonAddy_0_6_0.txt](https://github.com/anonaddy/docker/files/5433811/AnonAddy_0_6_0.txt)

**Comment by KevinRoebert** [comment]
Maybe #30 is a duplicate.

**Comment by crazy-max** [comment]
@djedje72 @KevinRoebert I've made some changes, can you test with `anonaddy/anonaddy:edge` image?

**Comment by KevinRoebert** [comment]
> 
> 
> @djedje72 @KevinRoebert I've made some changes, can you test with `anonaddy/anonaddy:edge` image?

Works for me.

**Comment by djedje72** [comment]
> @djedje72 @KevinRoebert I've made some changes, can you test with `anonaddy/anonaddy:edge` image?

Works for me too !
