### ISSUE TITLE
Replace Logo and background

### ISSUE THREAD

**Issue by djspacedevil** [anonaddy/docker#302]
### Description

Hello, 

It would be great if you could change the logo and the background via an ENV. This would mean that the login page would not make it immediately recognisable that it is an Addy.io installation.

BR

**Comment by willbrowningme** [comment]
I'm afraid I don't have any plans to add this.

If you want to make changes you can fork the repo and make them yourself there. 

You must state the changes and disclose the source as per the license - https://github.com/anonaddy/anonaddy/blob/master/LICENSE.md
