### ISSUE TITLE
Multi domains from ANONADDY_ALL_DOMAINS should be reflected in postfix virtual_mailbox_domains configuration

### ISSUE THREAD

**Issue by slurdge** [anonaddy/docker#32]
I didn't realize, but I have a local fix that is not upstream I believe.
Here this line `virtual_mailbox_domains ` should include all the domains from ANONADDY_ALL_DOMAINS 
https://github.com/anonaddy/docker/blob/3c3f88d9e643e6f725baa736c962175d4d0b4e24/rootfs/etc/cont-init.d/03-config.sh#L249
This is already the case for the first domain through \$mydomain, but the subsequent domains aren't put in this list and therefore will be rejected.

A simple sed is fixing this issue, e.g.:
```
docker-compose exec anonaddy sed -i 's/virtual_mailbox_domains = $mydomain, unsubscribe.$mydomain,/virtual_mailbox_domains = $mydomain, unsubscribe.$mydomain, example.net, unsubscribe.example.net,/' /etc/postfix/main.cf
docker-compose exec anonaddy postfix reload
```

But it would be better to include it in the config.sh script.

**Comment by slurdge** [comment]
@crazy-max Is there anything that I should do ?

**Comment by crazy-max** [comment]
@slurdge I don't think this is required because virtual mailbox domains already handle this through `mysql:/etc/postfix/mysql-virtual-alias-domains-and-subdomains.cf `? WDYT @willbrowningme?

**Comment by slurdge** [comment]
Hmm, true... I see the domains in the mysql query. I wonder why it didn't work... Let me do some more tests

**Comment by slurdge** [comment]
Ah! yes I see the problem.
The mysql query will only work for additional domains *with* a sub-domain of the user, not for top level. That's why the \$mydomain is needed. Therefore we need to also put the ANONADDY_ALL_DOMAINS domains directly (as for $mydomain). I believe this will also prevent a mysql query if it matches, which is good.

**Comment by crazy-max** [comment]
@slurdge Should be fixed with `anonaddy/anonaddy:edge`

**Comment by slurdge** [comment]
@crazy-max works fine on edge! Just two minor remarks:

- Since $mydomain should be the first domain from ANONADDY_DOMAIN, there is no need to repeat.
- You have an extra "," because you put it twice, in the first var and then add it for concatenation.

Nice work!

**Comment by crazy-max** [comment]
@slurdge 

Good call, now should be fixed in `anonaddy/anonaddy:edge`.

**Comment by slurdge** [comment]
Let's close!
