### ISSUE TITLE
Support DMARC and DKIM

### ISSUE THREAD

**Issue by M96268004** [anonaddy/docker#35]
Thanks for the docker image.

Would like to know if it is possible to add support for DMARC and DKIM into docker image?
Currently, the email I reply to anonymously most likely will go to spam folder at the first time, till the receiver while-list the email address.
I manually add DKIM and DMARC to the image, but the DKIM always not been signed when I reply.
Or if there is a way that I can add this from the image?
Thanks.

**Comment by crazy-max** [comment]
@M96268004 Now available in latest image
