### ISSUE TITLE
"anonaddy": executable file not found anymore after update from 0.6.0 

### ISSUE THREAD

**Issue by Flunkyball** [anonaddy/docker#43]
### Behaviour
The anonaddy executable is not found anymore after upgrading the docker container from 0.6.0 to the current version 0.7.1.
Furthermore login via the website is not possible as well. 
However, access via applications that are using API keys works as well as all normal operations for existing users.

#### Steps to reproduce this issue

1. Setup a anonaddy docker image version 0.6.0
2. Stop the container.
3. Update the container with "docker-compose pull"
4. Start the container again with docker-compose up -d

#### Expected behaviour

a) When executing "docker-compose exec anonaddy anonaddy list" the available administrative commands should be listed.
b) After calling the webapp in the browser and entering the correct credentials the user is forwarded to his status page etc.

#### Actual behaviour
a) The following error is displayed: "OCI runtime exec failed: exec failed: container_linux.go:370: starting container process caused: exec: "anonaddy": executable file not found in $PATH: unknown"

b) The login page is reloaded with no error message what so ever.

### Configuration

* Docker version (type `docker --version`) : Docker version 20.10.0, build 7287ab3
* Docker compose version if applicable (type `docker-compose --version`) :  docker-compose version 1.27.4, build 40524192
* Platform (Debian 9, Ubuntu 18.04, ...) : Debian 10
* System info (type `uname -a`) : Linux domain.com 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux

### Logs
Syslog reports on container startup various times:

Feb 27 16:00:03 server sh[4901]: #033[36manonaddy    |#033[0m /var/run/s6/etc/cont-init.d/04-svc-main.sh: line 7: /usr/local/bin/anonaddy: Permission denied
Feb 27 16:00:03 server sh[4901]: #033[36manonaddy    |#033[0m /var/run/s6/etc/cont-init.d/04-svc-main.sh: line 8: /usr/local/bin/anonaddy: Permission denied
Feb 27 16:00:03 server sh[4901]: #033[36manonaddy    |#033[0m /var/run/s6/etc/cont-init.d/04-svc-main.sh: line 9: /usr/local/bin/anonaddy: Permission denied
Feb 27 16:00:03 server sh[4901]: #033[36manonaddy    |#033[0m /var/run/s6/etc/cont-init.d/04-svc-main.sh: line 10: /usr/local/bin/anonaddy: Permission denied
Feb 27 16:00:03 server sh[4901]: #033[36manonaddy    |#033[0m /var/run/s6/etc/cont-init.d/04-svc-main.sh: line 11: /usr/local/bin/anonaddy: Permission denied

**Comment by crazy-max** [comment]
@Flunkyball 

Thanks for your feedback. Should be fixed now.

**Comment by Flunkyball** [comment]
@crazy-max 
Thank you for the fast fix. Just pulled the update and I can confirm it to be working now just fine.
