### ISSUE TITLE
Customize self-hosted environment

### ISSUE THREAD

**Issue by rajaseg** [anonaddy/docker#46]
Hi Thank you very much for the application. Is there a way to edit or modify self-hosted environment? I wanted to include

1. Upload custom logo
2. Modify mail templates to include custom logo and footer notes
3. Include custom terms page in registration page

**Comment by crazy-max** [comment]
@rajaseg This repo si related to the Docker image. Please open your issue on [anonaddy/anonaddy](https://github.com/anonaddy/anonaddy).

**Comment by rajaseg** [comment]
> @rajaseg This repo si related to the Docker image. Please open your issue on [anonaddy/anonaddy](https://github.com/anonaddy/anonaddy).

@crazy-max Thanks for the quick replay. I want to utilize docker image for self hosting. I have opened the issue https://github.com/anonaddy/docker/issues/46
