### ISSUE TITLE
Only supported ciphers are AES-128 and AES-256

### ISSUE THREAD

**Issue by Coderdude112** [anonaddy/docker#68]
Hello,

When starting to self host anonaddy at home I am unsure of what to use in the `ANONADDY_SECRET` of my .env file.
Every time the docker container restarts and I attempt to access the web interface, I get the following error in the logs:

```
2021/07/28 06:42:55 [error] 932#932: *6 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught RuntimeException: The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths. in /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:44
Stack trace:
#0 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(32): Illuminate\Encryption\Encrypter->__construct()
#1 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Container/Container.php(869): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}()

172.28.0.1 - - [28/Jul/2021:06:42:55 +0200] "GET / HTTP/1.1" 500 5 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0"

#2 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Container/Container.php(754): Illuminate\Container\Container->build()
#3 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\Container\Container->resolve()
#4 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\Foundation\Application->resolve()
#5 /var/www/anonaddy/vendor/lara...
```

I have found a workaround by executing the following on my system, but needing to do so everytime the docker container restarts:
```
docker-compose exec anonaddy php artisan key:generate
docker-compose exec anonaddy php artisan config:clear
```

What am I supposed to put in the `ANONADDY_SECRET` field of my .env file. Am I doing something else wrong??

Thanks for your help in advance.

**Comment by willbrowningme** [comment]
`ANONADDY_SECRET` is just a random string that is used for verifying custom domains with the TXT record. It can be anything e.g. `w9KkdYTbX3p5qH8srTLJdJTWrujJRS`, it is not related to the errors above.

The error you have is related to the `APP_KEY` and the Laravel encryptor. 

Those commands you have run should sort the issue, not sure why you need to run them each time the container restarts.

Does your app key looking like this?

```
APP_KEY=base64:dG/v+Dc73X/5wB4kKn/gjuaJucxR+TMrcTFuygOdWCQ=
```

**Comment by Coderdude112** [comment]
It looks very simmilar this is what the `APP_KEY` looks like in my case
```
APP_KEY=Pwx7y9NeSvjPdBR9nj5PNH+Yh23i1JT6sMfenzbgSYU=
```

If I do not run those two commands every time I start the container then attempting to access the web interface just gives me a blank page.

For the `ANONADDY_SECRET` can it really just be a random long string of characters like this:
```
ksjhdbfliawdbsfpibapwsihdbfpkabsdkfgauweibhrabwejhbifcjbpwuegrfbkhfbkjwbseo;uhfou
```

**Comment by willbrowningme** [comment]
Hmm, try adding base64 before your key so that it looks like this:

```
APP_KEY=base64:Pwx7y9NeSvjPdBR9nj5PNH+Yh23i1JT6sMfenzbgSYU=
```

Also make sure to change that key after testing if you are using it in production since you should never share it with anyone as it's used for encrypting cookies and data etc.

Yes it can be any long random string, it's only used here in the code - https://github.com/anonaddy/anonaddy/blob/master/app/Models/Domain.php#L196

**Comment by Coderdude112** [comment]
Yep that was it. I added `base64:` and then my key and that solved it.

Thanks for your help!!
