### ISSUE TITLE
DNS configuration

### ISSUE THREAD

**Issue by vonProteus** [anonaddy/docker#78]
Can you create section about DNS record to set?
with examples for MX SPF DMARC DKIM and others that are required for optimal operation
not to be consider as SPAM sender

**Comment by willbrowningme** [comment]
The correct DNS records can be found by having a quick read through the [self-hosting](https://anonaddy.com/self-hosting/) guide.

Here are some of the records you need:

| Type | Host               | Value                                                |
|------|--------------------|------------------------------------------------------|
| TXT  | @                  | v=spf1 mx ~all                                       |
| TXT  | *                  | v=spf1 mx ~all                                       |
| TXT  | default._domainkey | your key here...                                     |
| TXT  | _dmarc             | v=DMARC1; p=none; sp=none; adkim=r; aspf=r; pct=100; |

You can use a website such as [mail-tester.com](https://www.mail-tester.com/) to check if you are fully authenticated to send email.
