### ISSUE TITLE
sasl_passwd file has repeat entries after multiple container restarts

### ISSUE THREAD

**Issue by eleith** [anonaddy/docker#92]
### Behaviour

`/ets/postfix/sasl_passwd` has repeat entries after multiple `docker-compose start` and `docker-compose up -d`

#### Steps to reproduce this issue

1. set `POSTFIX_RELAYHOST` `POSTFIX_RELAYHOST_AUTH_ENABLE` `POSTFIX_RELAYHOST_USERNAME` and `POSTFIX_RELAYHOST_PASSWORD` in `anonaddy.env`
2. run `docker-compose stop` and `docker-compose up -d` a few times

#### Expected behaviour

`/ets/postfix/sasl_passwd` does not contain duplicate entries and remains stable

#### Actual behaviour

sometimes a new line gets added on top and sometimes a duplicate entry will appear (in fact, i think they alternate).

**Comment by eleith** [comment]
`postfix/master.cf` also exhibits this behavior, so it seems like this is not scoped to just one file, but many config files for which this image `cat` to the end of a file.

the main impact i'm seeing now is that i get warnings from postfix about duplicate entries. but there may be other impact longterm and it would be nice to be able to restart containers while still assuming stable config files

**Comment by crazy-max** [comment]
Thanks for your feedback will take a look.

**Comment by crazy-max** [comment]
Yeah so the issue is located here for the master.cf:

https://github.com/anonaddy/docker/blob/f0421db85ffaf6240c72d1e6f187f1f654def5dd/rootfs/etc/cont-init.d/03-config.sh#L341

We would need to templatize and put them in `rootfs/tpls` like we do for nginx and php I guess.
