### ISSUE TITLE
Usage of nginx as reverse proxy possible?

### ISSUE THREAD

**Issue by multimill** [anonaddy/docker#97]
Hello,

I just tried installing the app. Everything is working fine except the reverse proxy I tried to configure. I would like to use nginx.

So basically my nginx config looks like this:

```
server {

  server_name anon.mult1.com;

  location / {
      proxy_pass http://anon.mult1.com:8000/;
  }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/anon.mult1.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/anon.mult1.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = anon.mult1.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


  listen 80;

  server_name anon.mult1.com;
    return 404; # managed by Certbot


}
```

I can access the website just fine. But if I try to register an account I do get forwarded to anon.mult1.com:8000 and I don't get why this happens. My anonaddy.env does include this line:

`APP_URL=https://anon.mult1.com/`

What am I missing?

Thanks in advance!

**Comment by crazy-max** [comment]
@multimill I think this could be fixed by https://github.com/anonaddy/docker/pull/96#discussion_r785464039 in a follow-up.

Btw what's your issue with traefik?

**Comment by multimill** [comment]
I don't have a problem with traefik. But I have nevery used it so far and I want to host the app on a machine where other apps are served via nginx reverse proxy aswell. I guess I won't be able to run traefik with nginx on the same machine as they would interfere with the ports.  

I might try the traefik installation.

**Comment by crazy-max** [comment]
@multimill If you try it you'll never come back. Just saying :innocent:
